name: T3SL4Kredi
version: 31.01.2021
author: SYN_T3SL4
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
main: me.t3sl4.kredi.T3SL4Kredi

commands:
  kredim:
    description: Shows the player's credit amount.
  kredi:
    description: Main command of plugin.
